groups = {'01': 'Accommodation, eating and drinking', 
          '02': 'Commercial services', 
          '03': 'Attractions', 
          '04': 'Sport and entertainment', 
          '05': 'Education and health', 
          '06': 'Public Infrastructure', 
          '07': 'Manufacturing and production', 
          '09': 'Retail', 
          '10': 'Transport'}

categories = {'01': 'Accommodation', 
              '02': 'Eating and drinking', 
              '03': 'Construction services', 
              '04': 'Consultancies', 
              '05': 'Employment and career agencies', 
              '06': 'Engineering services', 
              '07': 'Contract services', 
              '08': 'IT, advertising, marketing and media services', 
              '09': 'Legal and financial', 
              '10': 'Personal, consumer and other services', 
              '11': 'Property and development services', 
              '12': 'Recycling services', 
              '13': 'Repair and servicing', 
              '14': 'Research and design', 
              '15': 'Transport, storage and delivery', 
              '60': 'Hire services', 
              '16': 'Botanical and zoological', 
              '17': 'Historical and cultural', 
              '18': 'Recreational', 
              '19': 'Landscape features', 
              '20': 'Tourism', 
              '58': 'Bodies of water', 
              '21': 'Sport and entertainment support services', 
              '22': 'Gambling', 
              '23': 'Outdoor pursuits', 
              '24': 'Sports complex', 
              '25': 'Venues, stage and screen', 
              '26': 'Animal welfare', 
              '27': 'Education support services', 
              '28': 'Health practitioners and establishments', 
              '29': 'Health support services', 
              '31': 'Primary, secondary and tertiary education', 
              '32': 'Recreational and vocational education', 
              '33': 'Central and local government', 
              '34': 'Infrastructure and facilities', 
              '35': 'Organisations', 
              '37': 'Consumer products', 
              '38': 'Extractive industries', 
              '39': 'Farming', 
              '40': 'Foodstuffs', 
              '41': 'Industrial features', 
              '42': 'Industrial products', 
              '46': 'Clothing and accessories', 
              '47': 'Food, drink and multi item retail', 
              '48': 'Household, office, leisure and garden', 
              '49': 'Motoring', 
              '53': 'Air', 
              '54': 'Road and rail', 
              '55': 'Walking', 
              '56': 'Water', 
              '57': 'Public transport, stations and infrastructure', 
              '59': 'Bus transport'}

classes = {'0003': 'Bed and breakfast and backpacker accommodation', 
           '0007': 'Self catering', 
           '0002': 'Camping, caravanning, mobile homes, holiday parks and centres', 
           '0008': 'Timeshare', 
           '0005': 'Hostels and refuges for the homeless', 
           '0009': 'Youth accommodation', 
           '0006': 'Hotels, motels, country houses and inns', 
           '0012': 'Banqueting and function rooms', 
           '0020': 'Fish and chip shops', 
           '0013': 'Cafes, snack bars and tea rooms', 
           '0025': 'Internet Cafes', 
           '0018': 'Fast food and takeaway outlets', 
           '0034': 'Pubs, bars and inns', 
           '0019': 'Fast food delivery services', 
           '0043': 'Restaurants', 
           '0779': 'Building and component suppliers', 
           '0053': 'Glaziers', 
           '0045': 'Building contractors', 
           '0044': 'Metalworkers including blacksmiths', 
           '0046': 'Construction completion services', 
           '0054': 'Painting and decorating services', 
           '0047': 'Construction plant', 
           '0055': 'Plasterers', 
           '0048': 'Cutting, drilling and welding services', 
           '0056': 'Plumbing and heating services', 
           '0063': 'Architectural and building-related consultants', 
           '0069': 'Image consultants', 
           '0064': 'Business-related consultants', 
           '0070': 'Interpretation and translation consultants', 
           '0065': 'Computer consultants', 
           '0071': 'Security consultants', 
           '0066': 'Construction service consultants', 
           '0072': 'Telecommunications consultants', 
           '0067': 'Feng shui consultants, furnishers and shop fitters', 
           '0074': 'Traffic management and transport-related consultants', 
           '0068': 'Food consultants', 
           '0075': 'Careers offices and armed forces recruitment', 
           '0078': 'Employment agencies', 
           '0076': 'Domestic staff and home help', 
           '0079': 'Modelling and theatrical agencies', 
           '0077': 'Driver agencies', 
           '0081': 'Nursing agencies', 
           '0083': 'Aviation engineers', 
           '0089': 'Instrumentation engineers', 
           '0084': 'Chemical engineers', 
           '0090': 'Marine engineers and services', 
           '0085': 'Civil engineers', 
           '0091': 'Mechanical engineers', 
           '0086': 'Electrical and electronic engineers', 
           '0092': 'Pneumatic engineers', 
           '0087': 'Hydraulic engineers', 
           '0093': 'Precision engineers', 
           '0088': 'Industrial engineers', 
           '0094': 'Structural engineers', 
           '0095': 'Agricultural contractors', 
           '0102': 'Drain and sewage clearance', 
           '0096': 'Aircraft charters', 
           '0105': 'Linen hire and washroom services', 
           '0098': 'Catering services', 
           '0107': 'Office services', 
           '0100': 'Contract cleaning services', 
           '0108': 'Packers', 
           '0101': 'Display and window dressers', 
           '0109': 'Pest and vermin control', 
           '0114': 'Advertising services', 
           '0124': 'Internet services', 
           '0115': 'Artists, illustrators and calligraphers', 
           '0125': 'Literary services', 
           '0116': 'Computer security', 
           '0126': 'Mailing and other information services', 
           '0117': 'Computer systems services', 
           '0127': 'Marketing services', 
           '0118': 'Concert/exhibition organisers and services', 
           '0128': 'Plate makers, print finishers and typesetters', 
           '0119': 'Database services', 
           '0129': 'Press and journalism services', 
           '0120': 'Desktop publishing services', 
           '0130': 'Printing and photocopying services', 
           '0121': 'Electronic and Internet publishers', 
           '0131': 'Recording studios and record companies', 
           '0122': 'Film and video services', 
           '0133': 'Telephone, telex and fax services', 
           '0123': 'General computer services', 
           '0134': 'Television and radio services', 
           '0135': 'Accountants and auditors', 
           '0138': 'Banks and building societies', 
           '0137': 'Auctioneers, auction rooms and valuers', 
           '0796': 'Franchise and holding company services', 
           '0141': 'Cash machines', 
           '0148': 'Fundraising services', 
           '0142': 'Cheque cashing', 
           '0149': 'Insurers and support activities', 
           '0795': 'Commodity dealers', 
           '0150': 'Mortgage and financial lenders', 
           '0143': 'Company registration and trademarks', 
           '0151': 'Pawnbrokers', 
           '0144': 'Copyright and patent', 
           '0811': 'PayPoint® locations', 
           '0145': 'Credit reference agencies', 
           '0829': 'Pension and fund management', 
           '0140': 'Currency conversion and money transfers', 
           '0154': 'Solicitors, advocates and notaries public', 
           '0146': 'Debt collecting agencies', 
           '0773': 'Stocks, shares and unit trusts', 
           '0147': 'Financial advice services', 
           '0823': 'Adult services', 
           '0174': 'Party organisers', 
           '0155': 'Astrologers, clairvoyants and palmists', 
           '0175': 'Personalisation', 
           '0158': 'Cleaning services', 
           '0177': 'Photographic services', 
           '0160': 'Customer service centres', 
           '0826': 'Printing on garments', 
           '0161': 'CV writers', 
           '0775': 'Sculptors, woodworkers and stonemasons', 
           '0162': 'Detective and investigation agencies', 
           '0818': 'Sewage Services', 
           '0112': 'Event Ticket Agents and Box Office', 
           '0822': 'Slimming clubs and services', 
           '0165': 'Funeral and associated services', 
           '0821': 'Spas', 
           '0156': 'Hair and beauty services', 
           '0179': 'Sports services', 
           '0167': 'Headquarters, administration and central offices', 
           '0776': 'Tailoring and clothing alteration', 
           '0166': 'Historical research', 
           '0180': 'Tattooing and piercing services', 
           '0103': 'Hotel Booking Agencies', 
           '0182': 'Trophies and engraving services', 
           '0169': 'Introduction and dating agencies', 
           '0777': 'Vehicle breakdown and recovery services', 
           '0170': 'Lock, key and security services', 
           '0183': 'Vehicle cleaning services', 
           '0171': 'Message and greeting services', 
           '0185': 'Weather services', 
           '0173': 'Motoring organisations', 
           '0186': 'Wedding services', 
           '0774': 'Musicians, orchestras and composers', 
           '0188': 'Window cleaners', 
           '0189': 'Commercial property letting', 
           '0195': 'Property information services', 
           '0191': 'Estate and property management', 
           '0192': 'Property letting', 
           '0194': 'Property development services', 
           '0190': 'Property sales', 
           '0199': 'Clearance and salvage dealers', 
           '0200': 'Scrap metal dealers and breakers yards', 
           '0198': 'Rag merchants', 
           '0202': 'Waste paper merchants', 
           '0196': 'Recycling, reclamation and disposal', 
           '0204': 'Building repairs', 
           '0793': 'Shoe repairs', 
           '0205': 'Electrical equipment repair and servicing', 
           '0210': 'Sports and leisure equipment repair', 
           '0206': 'Household repairs and restoration', 
           '0211': 'Tool repairs', 
           '0207': 'Industrial repairs and servicing', 
           '0212': 'Vehicle repair, testing and servicing', 
           '0209': 'Service industry equipment repairs', 
           '0214': 'Design services', 
           '0217': 'Testing and analysis services', 
           '0216': 'Research services', 
           '0218': 'Airlines and airline services', 
           '0224': 'Ferry and cruise companies', 
           '0219': 'Animal transportation', 
           '0225': 'Import and export services', 
           '0221': 'Container and storage', 
           '0227': 'Railway related services', 
           '0222': 'Courier, delivery and messenger', 
           '0228': 'Removals and shipping agents', 
           '0223': 'Distribution and haulage', 
           '0230': 'Taxi services', 
           '0097': 'Boat hiring services',
           '0104': 'Leisure equipment hirings',
           '0270': 'Bouncy castles and inflatables hire',
           '0110': 'Renting and leasing of personal and household goods',
           '0159': 'Clothing hire',
           '0111': 'Sound, light and vision service and equipment hire',
           '0099': 'Construction and tool hire',
           '0113': 'Vehicle hire and rental',
           '0231': 'Aquaria and sea life centres',
           '0236': 'Horticultural attractions',
           '0232': 'Bird reserves, collections and sanctuaries',
           '0237': 'Salmon ladders',
           '0233': 'Butterfly farms',
           '0239': 'Zoos and animal collections',
           '0235': 'Farm-based attractions',
           '0240': 'Archaeological sites',
           '0244': 'Historic buildings including castles, forts and abbeys',
           '0813': 'Art galleries',
           '0246': 'Historical ships',
           '0241': 'Battlefields',
           '0248': 'Museums',
           '0245': 'Historic and ceremonial structures'      
}